# Generated by Django 5.0.2 on 2024-03-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("PAID", "paid"),
                            ("EXPIRED", "expired"),
                        ],
                        default="PENDING",
                        max_length=40,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("PAYMENT", "payment"), ("FINE", "fine")],
                        default="PAYMENT",
                        max_length=40,
                    ),
                ),
                ("session_url", models.TextField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "money_to_be_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowing.borrowing",
                    ),
                ),
            ],
        ),
    ]
